### ISSUE TITLE
Unable to provide resource management values for rlsd

### ISSUE THREAD

**Issue by stefanbethke** [T-Systems-MMS/cmcc-operator#51]
**Describe the bug**
When using the following snippet:
```
components:
...
 - type: content-server
    kind: rls
    resources:
      limits: ...
```

and with.rls is 0, an error message is shown: 
```
```

It should be possible to have the definition of parameters for the component even when the current confiration will not create it.

**To Reproduce**
See above
