### ISSUE TITLE
Option to configure allowPrivilegeEscalation: false

### ISSUE THREAD

**Issue by hektor1966** [T-Systems-MMS/cmcc-operator#79]
**Is your feature request related to a problem? Please describe.**

For security reasons, we must be able to configure  
allowPrivilegeEscalation: false 
for container as securityContext .

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Describe the solution you'd like**

Description how this can be configured in the operator.

**Comment by stefanbethke** [comment]
@hektor1966 Thanks for the suggestion! Do you see any reason for making this configurable, or do you think this should be the default for all pods?

**Comment by stefanbethke** [comment]
Thinking about it, I tend towards adding a securityContext and podSecurityContext to the components and the default config, so people can add whatever they deem appropriate in their situation. It would then be possible to say
```
defaults:
  podSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
```
or even set that for individual components.
